/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Controladores.CtrlConvertirLatextoXML;
import Controladores.CtrlConvertirXMLtoLatex;
import Controladores.CtrlInicio;
import java.io.File;
import javax.swing.JFileChooser;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 * Vista Convertir examen XML a LaTeX
 * @author miguelhernandez
 */
public class ConvertirXMLLatex extends javax.swing.JFrame {
    private String direccionPadre;
    JFileChooser fc;
    /**
     * Creates new form ConvertirXMLLatex
     */
    public ConvertirXMLLatex() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblConvertirExamen = new javax.swing.JLabel();
        lblAgregueDireccion = new javax.swing.JLabel();
        lblDireccionExamen = new javax.swing.JLabel();
        txtDireccionOrigen = new javax.swing.JTextField();
        btnAgregarArchivo = new javax.swing.JButton();
        btnConvertirExamen = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 720));

        lblConvertirExamen.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        lblConvertirExamen.setText("Convertir un examen de XML Moodle a LaTeX");

        lblAgregueDireccion.setText("Agregue el examen Moodle XML");

        lblDireccionExamen.setText("Examen Moodle XML:");

        btnAgregarArchivo.setText("Agregar examen");
        btnAgregarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarArchivoActionPerformed(evt);
            }
        });

        btnConvertirExamen.setText("Guardar examen");
        btnConvertirExamen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertirExamenActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addComponent(lblConvertirExamen))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblDireccionExamen)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAgregueDireccion)
                                    .addComponent(txtDireccionOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnConvertirExamen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAgregarArchivo, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(254, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(lblConvertirExamen)
                .addGap(70, 70, 70)
                .addComponent(lblAgregueDireccion)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccionExamen)
                    .addComponent(txtDireccionOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarArchivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 293, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConvertirExamen, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(107, 107, 107))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Muestra una ventana para escoger el archivo
     * @param evt Evento sobre el botón para escoger el archivo
     */
    private void btnAgregarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarArchivoActionPerformed
        JFileChooser escogerDireccion = new JFileChooser();
        escogerDireccion.showOpenDialog(this);
        String direc = escogerDireccion.getSelectedFile().getAbsolutePath();
        direccionPadre = escogerDireccion.getSelectedFile().getParent();
        if (direc.contains(".xml")) {
            //checar si existe el archivo 
            File archivo = new File(direc);
            if (archivo.exists()) {
                txtDireccionOrigen.setText(direc);
                txtDireccionOrigen.setEditable(false);
            } else {
                showMessageDialog(null, "El examen no existe en la ruta especificada");
            }

        } else {
            showMessageDialog(null, "Tiene que elegir un examen Moodle XML");
        }
        
        
        
        
        
        
        
    }//GEN-LAST:event_btnAgregarArchivoActionPerformed

   /**
     * Botón para cancelar y regresar a la vista Inicio
     * @param evt Evento sobre el botón para regresar al inicio
     */
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        CtrlInicio CI = new CtrlInicio(4);
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed
    /**
     * Botón para comenzar con la conversion del examen XML Moodle a LaTeX
     * @param evt Evento sobre el boton para iniciar la conversión
     */
    private void btnConvertirExamenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertirExamenActionPerformed
        String direccionOrigen,direccionDestino;
        direccionOrigen=txtDireccionOrigen.getText();
        fc = new JFileChooser();
        
        if (!direccionOrigen.isEmpty()) {

            int returnVal = fc.showSaveDialog(this);
            if (returnVal == JFileChooser.APPROVE_OPTION) {
                
                File file = fc.getSelectedFile();
                if (file.getName().contains(".tex")) {
                    if (file.exists()) {
                        showMessageDialog(null, "Ese nombre de examen ya existe en la ruta especificada");
                    } else {

                        direccionDestino = file.getAbsolutePath();
                        
                        
                        
                        CtrlConvertirXMLtoLatex CXTL = new CtrlConvertirXMLtoLatex(direccionOrigen,direccionDestino,direccionPadre);
                        
                    }

                } else if (file.getName().isEmpty()) {
                    showMessageDialog(null, "Debe escribir el nombre del examen LaTeX");
                } else {
                    showMessageDialog(null, "La terminación del nombre del examen debe ser .tex");
                }

                
            } else {
                //log.append("Cancelando");
            }
        } else {
            showMessageDialog(null, "Necesita agregar un examen Moodle XML");

        }
        
        //direccionDestino=txtDireccionDestino.getText();
        
        //showMessageDialog(null, "Examen creado");
    }//GEN-LAST:event_btnConvertirExamenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConvertirXMLLatex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConvertirXMLLatex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConvertirXMLLatex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConvertirXMLLatex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConvertirXMLLatex().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarArchivo;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConvertirExamen;
    private javax.swing.JLabel lblAgregueDireccion;
    private javax.swing.JLabel lblConvertirExamen;
    private javax.swing.JLabel lblDireccionExamen;
    private javax.swing.JTextField txtDireccionOrigen;
    // End of variables declaration//GEN-END:variables
}
